<?php
return [
  'SUPABASE_SERVICE_ROLE' => getenv('SUPABASE_SERVICE_ROLE'),
  'SMTP_PASS' => getenv('SMTP_PASS'),
  'CRON_TOKEN_FOLLOWUP' => getenv('CRON_TOKEN_FOLLOWUP'),
  'CRON_TOKEN_PORTAL' => getenv('CRON_TOKEN_PORTAL'),

  // Stripe
  'STRIPE_SECRET_KEY' => getenv('STRIPE_SECRET_KEY'),
  'STRIPE_WEBHOOK_SECRET' => getenv('STRIPE_WEBHOOK_SECRET'),
  'STRIPE_PRICE_ID' => getenv('STRIPE_PRICE_ID'),
];
define('DEMO_CLEANUP_TOKEN', getenv('DEMO_CLEANUP_TOKEN'));
